# https://starship.rs/config/
"$schema"="https://starship.rs/config-schema.json"

# https://catppuccin.com/palette
palette = "catppuccin_mocha"

format = """
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$sudo\
$status\
$character"""

right_format="""
$cmd_duration"""

add_newline=false
command_timeout=1000

# https://starship.rs/config/#character
[character]
success_symbol = "[➜](bold fg:green)"
error_symbol = "[✖](bold fg:red)"
vimcmd_symbol = "[](bold fg:creen)"
vimcmd_replace_one_symbol = "[](bold fg:purple)"
vimcmd_replace_symbol = "[](bold fg:purple)"
vimcmd_visual_symbol = "[](bold fg:lavender)"

# https://starship.rs/config/#directory
[directory]
truncation_symbol = "…/"
style="bold green"

# https://starship.rs/config/#git-branch
[git_branch]
symbol = ""
#truncation_length = 24
format="[[$symbol $branch(:$remote_branch)](bold fg:mauve)]($style) "

# https://starship.rs/config/#git-status
[git_status]
deleted = "✖"
format = "[($all_status$ahead_behind )]($style)"

# https://starship.rs/config/#command-duration
[cmd_duration]
format="[$duration]($style)"
style="surface1"

# https://starship.rs/config/#python
[python]
format="[( ${virtualenv} )]($style)"
style="black bold dimmed"

# https://catppuccin.com/palette
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"

